In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os
os.environ['KAGGLE_CONFIG_DIR'] = '/content/drive/MyDrive/Kaggle/'

In [3]:
!kaggle datasets download -d pardeep19singh/icc-mens-world-cup-2023

Downloading icc-mens-world-cup-2023.zip to /content
  0% 0.00/102k [00:00<?, ?B/s]
100% 102k/102k [00:00<00:00, 129MB/s]

In [4]:
import zipfile
import pandas as pd

zip_file_path = '/content/icc-mens-world-cup-2023.zip'
extracted_folder = '/content/Cricket/'
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extracted_folder)

deliveries = pd.read_csv(extracted_folder+'deliveries.csv')
matches = pd.read_csv(extracted_folder+'matches.csv')
points_table = pd.read_csv(extracted_folder+'points_table.csv')

In [5]:
deliveries.shape

(17380, 22)

In [6]:
matches.shape

(32, 18)

In [7]:
points_table.shape

(10, 13)

In [8]:
matches.shape

(32, 18)

In [9]:
matches.columns

Index(['season', 'team1', 'team2', 'date', 'match_number', 'venue', 'city',
       'toss_winner', 'toss_decision', 'player_of_match', 'umpire1', 'umpire2',
       'reserve_umpire', 'match_referee', 'winner', 'winner_runs',
       'winner_wickets', 'match_type'],
      dtype='object')

In [10]:
matches_df = matches

In [11]:
column = ['season','date', 'match_number','umpire1', 'umpire2',
       'reserve_umpire', 'match_referee','winner_runs',
       'winner_wickets', 'match_type','toss_winner', 'toss_decision','player_of_match']

In [12]:
matches_df = matches_df.drop(columns=column)

In [13]:
rankings = {
    "India" : 1,
    "Australia" : 2,
    "South Africa" : 3,
    "Pakistan" : 4,
    "New Zealand" : 5,
    "England" : 6,
    "Sri Lanka" : 7,
    "Bangladesh" : 8,
    "Afghanistan" : 9,
    "Netherlands" : 14,
}

In [14]:
matches_df['team1_rank'] = matches_df['team1'].map(rankings)
matches_df['team2_rank'] = matches_df['team2'].map(rankings)

matches_df

,team1,team2,venue,city,winner,team1_rank,team2_rank
0,England,New Zealand,Narendra Modi Stadium,Ahmedabad,New Zealand,6,5
1,Pakistan,Netherlands,Rajiv Gandhi International Stadium,Hyderabad,Pakistan,4,14
2,Afghanistan,Bangladesh,Himachal Pradesh Cricket Association Stadium,Dharamsala,Bangladesh,9,8
3,South Africa,Sri Lanka,Arun Jaitley Stadium,Delhi,South Africa,3,7
4,Australia,India,MA Chidambaram Stadium,Chennai,India,2,1
5,New Zealand,Netherlands,Rajiv Gandhi International Stadium,Hyderabad,New Zealand,5,14
6,England,Bangladesh,Himachal Pradesh Cricket Association Stadium,Dharamsala,England,6,8
7,Sri Lanka,Pakistan,Rajiv Gandhi International Stadium,Hyderabad,Pakistan,7,4
8,Afghanistan,India,Arun Jaitley Stadium,Delhi,India,9,1
9,South Africa,Australia,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,South Africa,3,2
10,Bangladesh,New Zealand,MA Chidambaram Stadium,Chennai,New Zealand,8,5
11,Pakistan,India,Narendra Modi Stadium,Ahmedabad,India,4,1
12,Afghanistan,England,Arun Jaitley Stadium,Delhi,Afghanistan,9,6
13,Sri Lanka,Australia,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Australia,7,2
14,Netherlands,South Africa,Himachal Pradesh Cricket Association Stadium,Dharamsala,Netherlands,14,3
15,New Zealand,Afghanistan,MA Chidambaram Stadium,Chennai,New Zealand,5,9
16,Bangladesh,India,Maharashtra Cricket Association Stadium,Pune,India,8,1
17,Australia,Pakistan,M Chinnaswamy Stadium,Bengaluru,Australia,2,4
18,Netherlands,Sri Lanka,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Sri Lanka,14,7
19,South Africa,England,Wankhede Stadium,Mumbai,South Africa,3,6
20,New Zealand,India,Himachal Pradesh Cricket Association Stadium,Dharamsala,India,5,1
21,Pakistan,Afghanistan,MA Chidambaram Stadium,Chennai,Afghanistan,4,9
22,South Africa,Bangladesh,Wankhede Stadium,Mumbai,South Africa,3,8
23,Australia,Netherlands,Arun Jaitley Stadium,Delhi,Australia,2,14
24,England,Sri Lanka,M Chinnaswamy Stadium,Bengaluru,Sri Lanka,6,7
25,Pakistan,South Africa,MA Chidambaram Stadium,Chennai,South Africa,4,3
26,Australia,New Zealand,Himachal Pradesh Cricket Association Stadium,Dharamsala,Australia,2,5
27,Netherlands,Bangladesh,Eden Gardens,Kolkata,Netherlands,14,8
28,India,England,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,India,1,6
29,Sri Lanka,Afghanistan,Maharashtra Cricket Association Stadium,Pune,Afghanistan,7,9
30,Bangladesh,Pakistan,Eden Gardens,Kolkata,Pakistan,8,4
31,South Africa,New Zealand,Maharashtra Cricket Association Stadium,Pune,South Africa,3,5

In [15]:
matches_df.columns

Index(['team1', 'team2', 'venue', 'city', 'winner', 'team1_rank',
       'team2_rank'],
      dtype='object')

In [16]:
new_order = ['team1','team1_rank', 'team2','team2_rank', 'venue', 'city', 'winner',
       ]
matches_df = matches_df[new_order]
matches_df

,team1,team1_rank,team2,team2_rank,venue,city,winner
0,England,6,New Zealand,5,Narendra Modi Stadium,Ahmedabad,New Zealand
1,Pakistan,4,Netherlands,14,Rajiv Gandhi International Stadium,Hyderabad,Pakistan
2,Afghanistan,9,Bangladesh,8,Himachal Pradesh Cricket Association Stadium,Dharamsala,Bangladesh
3,South Africa,3,Sri Lanka,7,Arun Jaitley Stadium,Delhi,South Africa
4,Australia,2,India,1,MA Chidambaram Stadium,Chennai,India
5,New Zealand,5,Netherlands,14,Rajiv Gandhi International Stadium,Hyderabad,New Zealand
6,England,6,Bangladesh,8,Himachal Pradesh Cricket Association Stadium,Dharamsala,England
7,Sri Lanka,7,Pakistan,4,Rajiv Gandhi International Stadium,Hyderabad,Pakistan
8,Afghanistan,9,India,1,Arun Jaitley Stadium,Delhi,India
9,South Africa,3,Australia,2,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,South Africa
10,Bangladesh,8,New Zealand,5,MA Chidambaram Stadium,Chennai,New Zealand
11,Pakistan,4,India,1,Narendra Modi Stadium,Ahmedabad,India
12,Afghanistan,9,England,6,Arun Jaitley Stadium,Delhi,Afghanistan
13,Sri Lanka,7,Australia,2,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Australia
14,Netherlands,14,South Africa,3,Himachal Pradesh Cricket Association Stadium,Dharamsala,Netherlands
15,New Zealand,5,Afghanistan,9,MA Chidambaram Stadium,Chennai,New Zealand
16,Bangladesh,8,India,1,Maharashtra Cricket Association Stadium,Pune,India
17,Australia,2,Pakistan,4,M Chinnaswamy Stadium,Bengaluru,Australia
18,Netherlands,14,Sri Lanka,7,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Sri Lanka
19,South Africa,3,England,6,Wankhede Stadium,Mumbai,South Africa
20,New Zealand,5,India,1,Himachal Pradesh Cricket Association Stadium,Dharamsala,India
21,Pakistan,4,Afghanistan,9,MA Chidambaram Stadium,Chennai,Afghanistan
22,South Africa,3,Bangladesh,8,Wankhede Stadium,Mumbai,South Africa
23,Australia,2,Netherlands,14,Arun Jaitley Stadium,Delhi,Australia
24,England,6,Sri Lanka,7,M Chinnaswamy Stadium,Bengaluru,Sri Lanka
25,Pakistan,4,South Africa,3,MA Chidambaram Stadium,Chennai,South Africa
26,Australia,2,New Zealand,5,Himachal Pradesh Cricket Association Stadium,Dharamsala,Australia
27,Netherlands,14,Bangladesh,8,Eden Gardens,Kolkata,Netherlands
28,India,1,England,6,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,India
29,Sri Lanka,7,Afghanistan,9,Maharashtra Cricket Association Stadium,Pune,Afghanistan
30,Bangladesh,8,Pakistan,4,Eden Gardens,Kolkata,Pakistan
31,South Africa,3,New Zealand,5,Maharashtra Cricket Association Stadium,Pune,South Africa

In [17]:
cleaned = matches_df
cleaned = cleaned.reset_index(drop=True)
cleaned.loc[cleaned['winner'] == cleaned['team2'], 'winning_team']=2
cleaned.loc[cleaned['winner'] == cleaned['team1'], 'winning_team']=1
cleaned = cleaned.drop(['winner'], axis=1)
cleaned['winning_team']=cleaned['winning_team'].astype(int)
cleaned

,team1,team1_rank,team2,team2_rank,venue,city,winning_team
0,England,6,New Zealand,5,Narendra Modi Stadium,Ahmedabad,2
1,Pakistan,4,Netherlands,14,Rajiv Gandhi International Stadium,Hyderabad,1
2,Afghanistan,9,Bangladesh,8,Himachal Pradesh Cricket Association Stadium,Dharamsala,2
3,South Africa,3,Sri Lanka,7,Arun Jaitley Stadium,Delhi,1
4,Australia,2,India,1,MA Chidambaram Stadium,Chennai,2
5,New Zealand,5,Netherlands,14,Rajiv Gandhi International Stadium,Hyderabad,1
6,England,6,Bangladesh,8,Himachal Pradesh Cricket Association Stadium,Dharamsala,1
7,Sri Lanka,7,Pakistan,4,Rajiv Gandhi International Stadium,Hyderabad,2
8,Afghanistan,9,India,1,Arun Jaitley Stadium,Delhi,2
9,South Africa,3,Australia,2,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,1
10,Bangladesh,8,New Zealand,5,MA Chidambaram Stadium,Chennai,2
11,Pakistan,4,India,1,Narendra Modi Stadium,Ahmedabad,2
12,Afghanistan,9,England,6,Arun Jaitley Stadium,Delhi,1
13,Sri Lanka,7,Australia,2,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,2
14,Netherlands,14,South Africa,3,Himachal Pradesh Cricket Association Stadium,Dharamsala,1
15,New Zealand,5,Afghanistan,9,MA Chidambaram Stadium,Chennai,1
16,Bangladesh,8,India,1,Maharashtra Cricket Association Stadium,Pune,2
17,Australia,2,Pakistan,4,M Chinnaswamy Stadium,Bengaluru,1
18,Netherlands,14,Sri Lanka,7,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,2
19,South Africa,3,England,6,Wankhede Stadium,Mumbai,1
20,New Zealand,5,India,1,Himachal Pradesh Cricket Association Stadium,Dharamsala,2
21,Pakistan,4,Afghanistan,9,MA Chidambaram Stadium,Chennai,2
22,South Africa,3,Bangladesh,8,Wankhede Stadium,Mumbai,1
23,Australia,2,Netherlands,14,Arun Jaitley Stadium,Delhi,1
24,England,6,Sri Lanka,7,M Chinnaswamy Stadium,Bengaluru,2
25,Pakistan,4,South Africa,3,MA Chidambaram Stadium,Chennai,2
26,Australia,2,New Zealand,5,Himachal Pradesh Cricket Association Stadium,Dharamsala,1
27,Netherlands,14,Bangladesh,8,Eden Gardens,Kolkata,1
28,India,1,England,6,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,1
29,Sri Lanka,7,Afghanistan,9,Maharashtra Cricket Association Stadium,Pune,2
30,Bangladesh,8,Pakistan,4,Eden Gardens,Kolkata,2
31,South Africa,3,New Zealand,5,Maharashtra Cricket Association Stadium,Pune,1

In [18]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

X = cleaned.drop(columns = ['winning_team'])
y = cleaned['winning_team']
# One-Hot Encoding

dfc = pd.get_dummies(X, columns=['team1', 'team2', 'venue', 'city',], prefix='encoded',drop_first=True)

# Print the final DataFrame with label-encoded and one-hot encoded columns
dfc

,team1_rank,team2_rank,encoded_Australia,encoded_Bangladesh,encoded_England,encoded_India,encoded_Netherlands,encoded_New Zealand,encoded_Pakistan,encoded_South Africa,...,encoded_Wankhede Stadium,encoded_Bengaluru,encoded_Chennai,encoded_Delhi,encoded_Dharamsala,encoded_Hyderabad,encoded_Kolkata,encoded_Lucknow,encoded_Mumbai,encoded_Pune
0,6,5,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,4,14,0,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
2,9,8,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,3,7,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
4,2,1,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
5,5,14,0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
6,6,8,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
7,7,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
8,9,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
9,3,2,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
10,8,5,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
11,4,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
12,9,6,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
13,7,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
14,14,3,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
15,5,9,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
16,8,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
17,2,4,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
18,14,7,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
19,3,6,0,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,1,0
20,5,1,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
21,4,9,0,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
22,3,8,0,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,1,0
23,2,14,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
24,6,7,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
25,4,3,0,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
26,2,5,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
27,14,8,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
28,1,6,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
29,7,9,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
30,8,4,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
31,3,5,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1

In [19]:
y

0     2
1     1
2     2
3     1
4     2
5     1
6     1
7     2
8     2
9     1
10    2
11    2
12    1
13    2
14    1
15    1
16    2
17    1
18    2
19    1
20    2
21    2
22    1
23    1
24    2
25    2
26    1
27    1
28    1
29    2
30    2
31    1
Name: winning_team, dtype: int64

In [20]:
from sklearn.preprocessing import StandardScaler
numerical_features = ['team1_rank', 'team2_rank', ]
scaler = StandardScaler()
dfc[numerical_features] = scaler.fit_transform(dfc[numerical_features])
dfc

,team1_rank,team2_rank,encoded_Australia,encoded_Bangladesh,encoded_England,encoded_India,encoded_Netherlands,encoded_New Zealand,encoded_Pakistan,encoded_South Africa,...,encoded_Wankhede Stadium,encoded_Bengaluru,encoded_Chennai,encoded_Delhi,encoded_Dharamsala,encoded_Hyderabad,encoded_Kolkata,encoded_Lucknow,encoded_Mumbai,encoded_Pune
0,0.044976,-0.230651,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,-0.530714,2.229629,0,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
2,0.908510,0.589442,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,-0.818559,0.316078,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
4,-1.106403,-1.324109,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
5,-0.242869,2.229629,0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
6,0.044976,0.589442,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
7,0.332820,-0.504016,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
8,0.908510,-1.324109,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
9,-0.818559,-1.050745,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
10,0.620665,-0.230651,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
11,-0.530714,-1.324109,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
12,0.908510,0.042713,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
13,0.332820,-1.050745,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
14,2.347734,-0.777380,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
15,-0.242869,0.862807,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
16,0.620665,-1.324109,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
17,-1.106403,-0.504016,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
18,2.347734,0.316078,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
19,-0.818559,0.042713,0,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,1,0
20,-0.242869,-1.324109,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
21,-0.530714,0.862807,0,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
22,-0.818559,0.589442,0,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,1,0
23,-1.106403,2.229629,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
24,0.044976,0.316078,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
25,-0.530714,-0.777380,0,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
26,-1.106403,-0.230651,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
27,2.347734,0.589442,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
28,-1.394248,0.042713,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
29,0.332820,0.862807,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
30,0.620665,-0.504016,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
31,-0.818559,-0.230651,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1

In [21]:
y

0     2
1     1
2     2
3     1
4     2
5     1
6     1
7     2
8     2
9     1
10    2
11    2
12    1
13    2
14    1
15    1
16    2
17    1
18    2
19    1
20    2
21    2
22    1
23    1
24    2
25    2
26    1
27    1
28    1
29    2
30    2
31    1
Name: winning_team, dtype: int64

In [22]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score

# Assuming you have a DataFrame named 'df' with features and labels
# Adjust this based on your actual DataFrame structure


# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(dfc, y, test_size=0.2, )



# Define the model
model = Sequential()
model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
# model.add(Dropout(0.5))  # Optional: Dropout for regularization
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
# model.add(Dropout(0.5))  # Optional: Dropout for regularization
model.add(Dense(1, activation='sigmoid'))  # Sigmoid activation for binary classification

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=8, validation_split=0.2)

# Evaluate the model on the testing set
y_pred = model.predict(X_test)
y_pred_binary = (y_pred > 0.5).astype(int)

accuracy = accuracy_score(y_test, y_pred_binary)
print("Accuracy:", accuracy)

Epoch 1/10
3/3 [==============================] - 1s 81ms/step - loss: 0.7978 - accuracy: 0.0000e+00 - val_loss: 0.7630 - val_accuracy: 0.4000
Epoch 2/10
3/3 [==============================] - 0s 12ms/step - loss: 0.7280 - accuracy: 0.3000 - val_loss: 0.7052 - val_accuracy: 0.4000
Epoch 3/10
3/3 [==============================] - 0s 12ms/step - loss: 0.6723 - accuracy: 0.3500 - val_loss: 0.6527 - val_accuracy: 0.4000
Epoch 4/10
3/3 [==============================] - 0s 13ms/step - loss: 0.6288 - accuracy: 0.5000 - val_loss: 0.6079 - val_accuracy: 0.4000
Epoch 5/10
3/3 [==============================] - 0s 14ms/step - loss: 0.5962 - accuracy: 0.5500 - val_loss: 0.5688 - val_accuracy: 0.4000
Epoch 6/10
3/3 [==============================] - 0s 14ms/step - loss: 0.5591 - accuracy: 0.5500 - val_loss: 0.5349 - val_accuracy: 0.4000
Epoch 7/10
3/3 [==============================] - 0s 13ms/step - loss: 0.5235 - accuracy: 0.5500 - val_loss: 0.4902 - val_accuracy: 0.4000
Epoch 8/10
3/3 [==============================] - 0s 12ms/step - loss: 0.4788 - accuracy: 0.5500 - val_loss: 0.4397 - val_accuracy: 0.4000
Epoch 9/10
3/3 [==============================] - 0s 13ms/step - loss: 0.4275 - accuracy: 0.5500 - val_loss: 0.3845 - val_accuracy: 0.4000
Epoch 10/10
3/3 [==============================] - 0s 13ms/step - loss: 0.3710 - accuracy: 0.5500 - val_loss: 0.3211 - val_accuracy: 0.4000
1/1 [==============================] - 0s 63ms/step
Accuracy: 0.42857142857142855

In [23]:
print(y_test)
print(y_pred_binary)

0     2
25    2
15    1
9     1
7     2
8     2
28    1
Name: winning_team, dtype: int64
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]

In [24]:
data = {
    'team1': ['India', 'South Africa'],
    'team2': ['New Zealand', 'Australia'],
    'venue': ['Wankhede Stadium', 'Eden Gardens'],
    'city': ['Mumbai', 'Kolkata'],
    'team1_rank': [1, 3],
    'team2_rank': [5, 2]
}

# Create DataFrame
test = pd.DataFrame(data)
test

,team1,team2,venue,city,team1_rank,team2_rank
0,India,New Zealand,Wankhede Stadium,Mumbai,1,5
1,South Africa,Australia,Eden Gardens,Kolkata,3,2

In [25]:
df1 = test
df2 = cleaned

# Concatenate the DataFrames
combined_df = pd.concat([df1, df2], ignore_index=True)

# Display the combined DataFrame
combined_df

,team1,team2,venue,city,team1_rank,team2_rank,winning_team
0,India,New Zealand,Wankhede Stadium,Mumbai,1,5,NaN
1,South Africa,Australia,Eden Gardens,Kolkata,3,2,NaN
2,England,New Zealand,Narendra Modi Stadium,Ahmedabad,6,5,2.0
3,Pakistan,Netherlands,Rajiv Gandhi International Stadium,Hyderabad,4,14,1.0
4,Afghanistan,Bangladesh,Himachal Pradesh Cricket Association Stadium,Dharamsala,9,8,2.0
5,South Africa,Sri Lanka,Arun Jaitley Stadium,Delhi,3,7,1.0
6,Australia,India,MA Chidambaram Stadium,Chennai,2,1,2.0
7,New Zealand,Netherlands,Rajiv Gandhi International Stadium,Hyderabad,5,14,1.0
8,England,Bangladesh,Himachal Pradesh Cricket Association Stadium,Dharamsala,6,8,1.0
9,Sri Lanka,Pakistan,Rajiv Gandhi International Stadium,Hyderabad,7,4,2.0
10,Afghanistan,India,Arun Jaitley Stadium,Delhi,9,1,2.0
11,South Africa,Australia,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,3,2,1.0
12,Bangladesh,New Zealand,MA Chidambaram Stadium,Chennai,8,5,2.0
13,Pakistan,India,Narendra Modi Stadium,Ahmedabad,4,1,2.0
14,Afghanistan,England,Arun Jaitley Stadium,Delhi,9,6,1.0
15,Sri Lanka,Australia,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,7,2,2.0
16,Netherlands,South Africa,Himachal Pradesh Cricket Association Stadium,Dharamsala,14,3,1.0
17,New Zealand,Afghanistan,MA Chidambaram Stadium,Chennai,5,9,1.0
18,Bangladesh,India,Maharashtra Cricket Association Stadium,Pune,8,1,2.0
19,Australia,Pakistan,M Chinnaswamy Stadium,Bengaluru,2,4,1.0
20,Netherlands,Sri Lanka,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,14,7,2.0
21,South Africa,England,Wankhede Stadium,Mumbai,3,6,1.0
22,New Zealand,India,Himachal Pradesh Cricket Association Stadium,Dharamsala,5,1,2.0
23,Pakistan,Afghanistan,MA Chidambaram Stadium,Chennai,4,9,2.0
24,South Africa,Bangladesh,Wankhede Stadium,Mumbai,3,8,1.0
25,Australia,Netherlands,Arun Jaitley Stadium,Delhi,2,14,1.0
26,England,Sri Lanka,M Chinnaswamy Stadium,Bengaluru,6,7,2.0
27,Pakistan,South Africa,MA Chidambaram Stadium,Chennai,4,3,2.0
28,Australia,New Zealand,Himachal Pradesh Cricket Association Stadium,Dharamsala,2,5,1.0
29,Netherlands,Bangladesh,Eden Gardens,Kolkata,14,8,1.0
30,India,England,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,1,6,1.0
31,Sri Lanka,Afghanistan,Maharashtra Cricket Association Stadium,Pune,7,9,2.0
32,Bangladesh,Pakistan,Eden Gardens,Kolkata,8,4,2.0
33,South Africa,New Zealand,Maharashtra Cricket Association Stadium,Pune,3,5,1.0

In [26]:
test_df = pd.get_dummies(combined_df, columns=['team1', 'team2', 'venue', 'city',], prefix='encoded', drop_first=True)

# Print the final DataFrame with label-encoded and one-hot encoded columns
test_df = test_df.drop(columns = ['winning_team'])
t_df = test_df.head(2)



numerical_features = ['team1_rank', 'team2_rank', ]
scaler = StandardScaler()
t_df[numerical_features] = scaler.fit_transform(t_df[numerical_features])
t_df

<ipython-input-26-46471189a0e2>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t_df[numerical_features] = scaler.fit_transform(t_df[numerical_features])

,team1_rank,team2_rank,encoded_Australia,encoded_Bangladesh,encoded_England,encoded_India,encoded_Netherlands,encoded_New Zealand,encoded_Pakistan,encoded_South Africa,...,encoded_Wankhede Stadium,encoded_Bengaluru,encoded_Chennai,encoded_Delhi,encoded_Dharamsala,encoded_Hyderabad,encoded_Kolkata,encoded_Lucknow,encoded_Mumbai,encoded_Pune
0,-1.0,1.0,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
1,1.0,-1.0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0

In [27]:
t_df.shape

(2, 38)

In [28]:
y_pred_sf = model.predict(t_df)
y_pred_binary_sf = (y_pred_sf > 0.5).astype(int)
y_pred_binary_sf

1/1 [==============================] - 0s 15ms/step

array([[1],
       [1]])

In [29]:
data = {'winning_team': [1,1]}
data = pd.DataFrame(data)

df1 = data
df2 = pd.DataFrame(cleaned['winning_team'])

# Concatenate the DataFrames
new_df = pd.concat([df1, df2], ignore_index=True)

new_df

    winning_team
0              1
1              1
2              2
3              1
4              2
5              1
6              2
7              1
8              1
9              2
10             2
11             1
12             2
13             2
14             1
15             2
16             1
17             1
18             2
19             1
20             2
21             1
22             2
23             2
24             1
25             1
26             2
27             2
28             1
29             1
30             1
31             2
32             2
33             1

In [42]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score

# Assuming you have a DataFrame named 'df' with features and labels
# Adjust this based on your actual DataFrame structure


# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(test_df, new_df, test_size=0.2, )



# Define the model
model = Sequential()
model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
# model.add(Dropout(0.5))  # Optional: Dropout for regularization
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
# model.add(Dropout(0.5))  # Optional: Dropout for regularization
model.add(Dense(1, activation='sigmoid'))  # Sigmoid activation for binary classification

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=8, validation_split=0.2)

# Evaluate the model on the testing set
y_pred = model.predict(X_test)
y_pred_binary = (y_pred > 0.5).astype(int)

accuracy = accuracy_score(y_test, y_pred_binary)
print("Accuracy:", accuracy)

Epoch 1/10
3/3 [==============================] - 1s 67ms/step - loss: 0.9094 - accuracy: 0.0000e+00 - val_loss: 0.8233 - val_accuracy: 0.1667
Epoch 2/10
3/3 [==============================] - 0s 12ms/step - loss: 0.6176 - accuracy: 0.5238 - val_loss: 0.4719 - val_accuracy: 0.5000
Epoch 3/10
3/3 [==============================] - 0s 11ms/step - loss: 0.3116 - accuracy: 0.5238 - val_loss: 0.1558 - val_accuracy: 0.5000
Epoch 4/10
3/3 [==============================] - 0s 11ms/step - loss: 0.0991 - accuracy: 0.5238 - val_loss: -0.1438 - val_accuracy: 0.5000
Epoch 5/10
3/3 [==============================] - 0s 11ms/step - loss: -0.1294 - accuracy: 0.5238 - val_loss: -0.4351 - val_accuracy: 0.5000
Epoch 6/10
3/3 [==============================] - 0s 11ms/step - loss: -0.3337 - accuracy: 0.5238 - val_loss: -0.7239 - val_accuracy: 0.5000
Epoch 7/10
3/3 [==============================] - 0s 11ms/step - loss: -0.5251 - accuracy: 0.5238 - val_loss: -1.0054 - val_accuracy: 0.5000
Epoch 8/10
3/3 [==============================] - 0s 11ms/step - loss: -0.7113 - accuracy: 0.5238 - val_loss: -1.2983 - val_accuracy: 0.5000
Epoch 9/10
3/3 [==============================] - 0s 11ms/step - loss: -0.9165 - accuracy: 0.5238 - val_loss: -1.5973 - val_accuracy: 0.5000
Epoch 10/10
3/3 [==============================] - 0s 20ms/step - loss: -1.1575 - accuracy: 0.5238 - val_loss: -1.9234 - val_accuracy: 0.5000
1/1 [==============================] - 0s 61ms/step
Accuracy: 0.5714285714285714

In [37]:
final_data = {
    'team1': ['India'],
    'team2': ['South Africa'],
    'venue': ["Narendra Modi Stadium"],
    'city': ['Ahmedabad'],
    'team1_rank': [1],
    'team2_rank': [3]
}
data = pd.DataFrame(final_data)

In [38]:
df1 = test
df2 = cleaned

# Concatenate the DataFrames
combined_df = pd.concat([df1, df2], ignore_index=True)

# Display the combined DataFrame
combined_df

,team1,team2,venue,city,team1_rank,team2_rank,winning_team
0,India,New Zealand,Wankhede Stadium,Mumbai,1,5,NaN
1,South Africa,Australia,Eden Gardens,Kolkata,3,2,NaN
2,England,New Zealand,Narendra Modi Stadium,Ahmedabad,6,5,2.0
3,Pakistan,Netherlands,Rajiv Gandhi International Stadium,Hyderabad,4,14,1.0
4,Afghanistan,Bangladesh,Himachal Pradesh Cricket Association Stadium,Dharamsala,9,8,2.0
5,South Africa,Sri Lanka,Arun Jaitley Stadium,Delhi,3,7,1.0
6,Australia,India,MA Chidambaram Stadium,Chennai,2,1,2.0
7,New Zealand,Netherlands,Rajiv Gandhi International Stadium,Hyderabad,5,14,1.0
8,England,Bangladesh,Himachal Pradesh Cricket Association Stadium,Dharamsala,6,8,1.0
9,Sri Lanka,Pakistan,Rajiv Gandhi International Stadium,Hyderabad,7,4,2.0
10,Afghanistan,India,Arun Jaitley Stadium,Delhi,9,1,2.0
11,South Africa,Australia,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,3,2,1.0
12,Bangladesh,New Zealand,MA Chidambaram Stadium,Chennai,8,5,2.0
13,Pakistan,India,Narendra Modi Stadium,Ahmedabad,4,1,2.0
14,Afghanistan,England,Arun Jaitley Stadium,Delhi,9,6,1.0
15,Sri Lanka,Australia,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,7,2,2.0
16,Netherlands,South Africa,Himachal Pradesh Cricket Association Stadium,Dharamsala,14,3,1.0
17,New Zealand,Afghanistan,MA Chidambaram Stadium,Chennai,5,9,1.0
18,Bangladesh,India,Maharashtra Cricket Association Stadium,Pune,8,1,2.0
19,Australia,Pakistan,M Chinnaswamy Stadium,Bengaluru,2,4,1.0
20,Netherlands,Sri Lanka,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,14,7,2.0
21,South Africa,England,Wankhede Stadium,Mumbai,3,6,1.0
22,New Zealand,India,Himachal Pradesh Cricket Association Stadium,Dharamsala,5,1,2.0
23,Pakistan,Afghanistan,MA Chidambaram Stadium,Chennai,4,9,2.0
24,South Africa,Bangladesh,Wankhede Stadium,Mumbai,3,8,1.0
25,Australia,Netherlands,Arun Jaitley Stadium,Delhi,2,14,1.0
26,England,Sri Lanka,M Chinnaswamy Stadium,Bengaluru,6,7,2.0
27,Pakistan,South Africa,MA Chidambaram Stadium,Chennai,4,3,2.0
28,Australia,New Zealand,Himachal Pradesh Cricket Association Stadium,Dharamsala,2,5,1.0
29,Netherlands,Bangladesh,Eden Gardens,Kolkata,14,8,1.0
30,India,England,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,1,6,1.0
31,Sri Lanka,Afghanistan,Maharashtra Cricket Association Stadium,Pune,7,9,2.0
32,Bangladesh,Pakistan,Eden Gardens,Kolkata,8,4,2.0
33,South Africa,New Zealand,Maharashtra Cricket Association Stadium,Pune,3,5,1.0

In [48]:


test_df = pd.get_dummies(combined_df, columns=['team1', 'team2', 'venue', 'city',], prefix='encoded', drop_first=True)

# Print the final DataFrame with label-encoded and one-hot encoded columns
test_df = test_df.drop(columns = ['winning_team'])
tf_df = test_df.head(1)



numerical_features = ['team1_rank', 'team2_rank', ]
scaler = StandardScaler()
tf_df[numerical_features] = scaler.fit_transform(tf_df[numerical_features])
tf_df

<ipython-input-48-0eeb968f26f7>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tf_df[numerical_features] = scaler.fit_transform(tf_df[numerical_features])

,team1_rank,team2_rank,encoded_Australia,encoded_Bangladesh,encoded_England,encoded_India,encoded_Netherlands,encoded_New Zealand,encoded_Pakistan,encoded_South Africa,...,encoded_Wankhede Stadium,encoded_Bengaluru,encoded_Chennai,encoded_Delhi,encoded_Dharamsala,encoded_Hyderabad,encoded_Kolkata,encoded_Lucknow,encoded_Mumbai,encoded_Pune
0,0.0,0.0,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0

In [49]:
y_pred = model.predict(tf_df)
y_pred_binary = (y_pred > 0.5).astype(int)

1/1 [==============================] - 0s 13ms/step

In [50]:
y_pred_binary

array([[1]])