#IDM Project-3


#Team-02

###TASK-1
---


---


####Nirmal Shah 202311043
####Samarth Motka 202311023
####Darshit Kalariya 202311035
####Deepak Khatri 202311042
####Viraj Prajapati 202311069

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
os.environ['KAGGLE_CONFIG_DIR'] = '/content/drive/MyDrive/Kaggle/'

In [ ]:
!kaggle datasets download -d pardeep19singh/icc-mens-world-cup-2023

Downloading icc-mens-world-cup-2023.zip to /content
  0% 0.00/102k [00:00<?, ?B/s]
100% 102k/102k [00:00<00:00, 95.8MB/s]

In [ ]:
import zipfile
import pandas as pd

zip_file_path = '/content/icc-mens-world-cup-2023.zip'
extracted_folder = '/content/Cricket/'
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extracted_folder)

deliveries = pd.read_csv(extracted_folder+'deliveries.csv')
matches = pd.read_csv(extracted_folder+'matches.csv')
points_table = pd.read_csv(extracted_folder+'points_table.csv')

#Task 1
##Predciting that the current delivery will be noball or not

In [ ]:
deliveries

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.1,England,New Zealand,JM Bairstow,DJ Malan,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.2,England,New Zealand,JM Bairstow,DJ Malan,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.3,England,New Zealand,JM Bairstow,DJ Malan,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.4,England,New Zealand,DJ Malan,JM Bairstow,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.5,England,New Zealand,JM Bairstow,DJ Malan,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17375,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,34.5,New Zealand,South Africa,MJ Henry,GD Phillips,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17376,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,34.6,New Zealand,South Africa,MJ Henry,GD Phillips,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17377,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,35.1,New Zealand,South Africa,GD Phillips,MJ Henry,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17378,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,35.2,New Zealand,South Africa,GD Phillips,MJ Henry,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17379,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,35.3,New Zealand,South Africa,GD Phillips,MJ Henry,...,0,NaN,NaN,NaN,NaN,NaN,caught,GD Phillips,NaN,NaN

All the columns of deliveries is shown below

In [ ]:
deliveries.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed'],
      dtype='object')

We will be removing the features that will not be useful in predicting that the current delivery is noball or not

In [ ]:
d_df = deliveries
cd = [ 'season', 'start_date','other_wicket_type',
       'other_player_dismissed','penalty', 'wicket_type', 'player_dismissed',]
d_df = d_df.drop(columns=cd)
d_df

,match_id,venue,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,wides,noballs,byes,legbyes
0,1,"Narendra Modi Stadium, Ahmedabad",1,0.1,England,New Zealand,JM Bairstow,DJ Malan,TA Boult,0,0,NaN,NaN,NaN,NaN
1,1,"Narendra Modi Stadium, Ahmedabad",1,0.2,England,New Zealand,JM Bairstow,DJ Malan,TA Boult,6,0,NaN,NaN,NaN,NaN
2,1,"Narendra Modi Stadium, Ahmedabad",1,0.3,England,New Zealand,JM Bairstow,DJ Malan,TA Boult,1,0,NaN,NaN,NaN,NaN
3,1,"Narendra Modi Stadium, Ahmedabad",1,0.4,England,New Zealand,DJ Malan,JM Bairstow,TA Boult,1,0,NaN,NaN,NaN,NaN
4,1,"Narendra Modi Stadium, Ahmedabad",1,0.5,England,New Zealand,JM Bairstow,DJ Malan,TA Boult,4,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17375,32,"Maharashtra Cricket Association Stadium, Pune",2,34.5,New Zealand,South Africa,MJ Henry,GD Phillips,KA Maharaj,0,0,NaN,NaN,NaN,NaN
17376,32,"Maharashtra Cricket Association Stadium, Pune",2,34.6,New Zealand,South Africa,MJ Henry,GD Phillips,KA Maharaj,0,0,NaN,NaN,NaN,NaN
17377,32,"Maharashtra Cricket Association Stadium, Pune",2,35.1,New Zealand,South Africa,GD Phillips,MJ Henry,G Coetzee,0,0,NaN,NaN,NaN,NaN
17378,32,"Maharashtra Cricket Association Stadium, Pune",2,35.2,New Zealand,South Africa,GD Phillips,MJ Henry,G Coetzee,6,0,NaN,NaN,NaN,NaN
17379,32,"Maharashtra Cricket Association Stadium, Pune",2,35.3,New Zealand,South Africa,GD Phillips,MJ Henry,G Coetzee,0,0,NaN,NaN,NaN,NaN

Looking for null values, we can see null values below that can be just replaced by 0.

In [ ]:
d_df.isnull().sum()

match_id            0
venue               0
innings             0
ball                0
batting_team        0
bowling_team        0
striker             0
non_striker         0
bowler              0
runs_off_bat        0
extras              0
wides           16949
noballs         17338
byes            17354
legbyes         17263
dtype: int64

In [ ]:
filled = d_df.fillna(0)
filled.isnull().sum()

match_id        0
venue           0
innings         0
ball            0
batting_team    0
bowling_team    0
striker         0
non_striker     0
bowler          0
runs_off_bat    0
extras          0
wides           0
noballs         0
byes            0
legbyes         0
dtype: int64

Getting insights on unique values of each column.

In [ ]:
for columns in filled.columns:
  print("unique in " + columns)
  print(filled[columns].unique())
  print("\n")

unique in match_id
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19 20 21 22 10 23 24
 25 26 27 28 29 30 31 32]


unique in venue
['Narendra Modi Stadium, Ahmedabad'
 'Rajiv Gandhi International Stadium, Uppal, Hyderabad'
 'Himachal Pradesh Cricket Association Stadium, Dharamsala'
 'Arun Jaitley Stadium, Delhi' 'MA Chidambaram Stadium, Chepauk, Chennai'
 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow'
 'Maharashtra Cricket Association Stadium, Pune'
 'M Chinnaswamy Stadium, Bengaluru' 'Wankhede Stadium, Mumbai'
 'Eden Gardens, Kolkata']


unique in innings
[1 2]


unique in ball
[ 0.1  0.2  0.3  0.4  0.5  0.6  1.1  1.2  1.3  1.4  1.5  1.6  2.1  2.2
  2.3  2.4  2.5  2.6  3.1  3.2  3.3  3.4  3.5  3.6  4.1  4.2  4.3  4.4
  4.5  4.6  4.7  5.1  5.2  5.3  5.4  5.5  5.6  6.1  6.2  6.3  6.4  6.5
  6.6  6.7  7.1  7.2  7.3  7.4  7.5  7.6  8.1  8.2  8.3  8.4  8.5  8.6
  9.1  9.2  9.3  9.4  9.5  9.6 10.1 10.2 10.3 10.4 10.5 10.6 11.1 11.2
 11.3 11.4 11.5 11.6 12.1 12.2 12.3 12.4 12.5 12.6 13.1 13.2 13.3 13.4
 13.5 13.6 14.1 14.2 14.3 14.4 14.5 14.6 15.1 15.2 15.3 15.4 15.5 15.6
 16.1 16.2 16.3 16.4 16.5 16.6 17.1 17.2 17.3 17.4 17.5 17.6 18.1 18.2
 18.3 18.4 18.5 18.6 19.1 19.2 19.3 19.4 19.5 19.6 19.7 20.1 20.2 20.3
 20.4 20.5 20.6 21.1 21.2 21.3 21.4 21.5 21.6 22.1 22.2 22.3 22.4 22.5
 22.6 23.1 23.2 23.3 23.4 23.5 23.6 24.1 24.2 24.3 24.4 24.5 24.6 25.1
 25.2 25.3 25.4 25.5 25.6 26.1 26.2 26.3 26.4 26.5 26.6 27.1 27.2 27.3
 27.4 27.5 27.6 28.1 28.2 28.3 28.4 28.5 28.6 29.1 29.2 29.3 29.4 29.5
 29.6 30.1 30.2 30.3 30.4 30.5 30.6 31.1 31.2 31.3 31.4 31.5 31.6 32.1
 32.2 32.3 32.4 32.5 32.6 33.1 33.2 33.3 33.4 33.5 33.6 34.1 34.2 34.3
 34.4 34.5 34.6 35.1 35.2 35.3 35.4 35.5 35.6 36.1 36.2 36.3 36.4 36.5
 36.6 37.1 37.2 37.3 37.4 37.5 37.6 38.1 38.2 38.3 38.4 38.5 38.6 39.1
 39.2 39.3 39.4 39.5 39.6 40.1 40.2 40.3 40.4 40.5 40.6 41.1 41.2 41.3
 41.4 41.5 41.6 42.1 42.2 42.3 42.4 42.5 42.6 43.1 43.2 43.3 43.4 43.5
 43.6 44.1 44.2 44.3 44.4 44.5 44.6 45.1 45.2 45.3 45.4 45.5 45.6 46.1
 46.2 46.3 46.4 46.5 46.6 47.1 47.2 47.3 47.4 47.5 47.6 48.1 48.2 48.3
 48.4 48.5 48.6 49.1 49.2 49.3 49.4 49.5 49.6 49.7  5.7 24.7 32.7  6.8
 16.7 21.7 25.7 31.7 39.7 39.8 47.7  0.7  3.7  9.7  9.8 28.7 34.7 40.7
  1.7  1.8 14.7  2.7 15.7 17.7 20.7 28.8 33.7 42.7 48.7 48.8 13.7 23.7
 23.8 30.7 37.7 42.8 30.8 44.7 46.7 47.8 27.7 27.8 29.7 34.8  2.8  2.9
 45.7  7.7 11.7 17.8 33.8 35.7 38.7 41.7 11.8 36.7 36.8  8.7 10.7 12.7
 12.8 22.7 18.7 22.8 26.7 39.9  0.8  5.8  0.9  8.8 37.8 43.7 45.8 45.9
 46.8 14.8 31.8  9.9 48.9 21.8 43.8 13.8  4.8 19.8 29.8]


unique in batting_team
['England' 'New Zealand' 'Pakistan' 'Netherlands' 'Afghanistan'
 'Bangladesh' 'South Africa' 'Sri Lanka' 'Australia' 'India']


unique in bowling_team
['New Zealand' 'England' 'Netherlands' 'Pakistan' 'Bangladesh'
 'Afghanistan' 'Sri Lanka' 'South Africa' 'India' 'Australia']


unique in striker
['JM Bairstow' 'DJ Malan' 'JE Root' 'HC Brook' 'MM Ali' 'JC Buttler'
 'LS Livingstone' 'SM Curran' 'CR Woakes' 'AU Rashid' 'MA Wood'
 'DP Conway' 'WA Young' 'R Ravindra' 'Fakhar Zaman' 'Imam-ul-Haq'
 'Babar Azam' 'Mohammad Rizwan' 'Saud Shakeel' 'Iftikhar Ahmed'
 'Mohammad Nawaz' 'Shadab Khan' 'Hasan Ali' 'Shaheen Shah Afridi'
 'Haris Rauf' 'Vikramjit Singh' "MP O'Dowd" 'CN Ackermann' 'BFW de Leede'
 'AT Nidamanuru' 'SA Edwards' 'Saqib Zulfiqar' 'RE van der Merwe'
 'LV van Beek' 'A Dutt' 'PA van Meekeren' 'Rahmanullah Gurbaz'
 'Ibrahim Zadran' 'Rahmat Shah' 'Hashmatullah Shahidi' 'Najibullah Zadran'
 'Mohammad Nabi' 'Azmatullah Omarzai' 'Rashid Khan' 'Mujeeb Ur Rahman'
 'Naveen-ul-Haq' 'Fazalhaq Farooqi' 'Tanzid Hasan' 'Liton Das'
 'Mehedi Hasan Miraz' 'Nazmul Hossain Shanto' 'Shakib Al Hasan'
 'Mushfiqur Rahim' 'Q de Kock' 'T Bavuma' 'HE van der Dussen' 'AK Markram'
 'H Klaasen' 'DA Miller' 'M Jansen' 'P Nissanka' 'MDKJ Perera'
 'BKG Mendis' 'S Samarawickrama' 'KIC Asalanka' 'DM de Silva' 'MD Shanaka'
 'DN Wellalage' 'CAK Rajitha' 'M Pathirana' 'D Madushanka' 'DA Warner'
 'MR Marsh' 'SPD Smith' 'M Labuschagne' 'GJ Maxwell' 'AT Carey' 'C Green'
 'PJ Cummins' 'MA Starc' 'A Zampa' 'JR Hazlewood' 'RG Sharma'
 'Ishan Kishan' 'V Kohli' 'SS Iyer' 'KL Rahul' 'HH Pandya' 'DJ Mitchell'
 'TWM Latham' 'GD Phillips' 'MS Chapman' 'MJ Santner' 'MJ Henry'
 'SA Engelbrecht' 'R Klein' 'RJW Topley' 'Towhid Hridoy' 'Mahedi Hasan'
 'Taskin Ahmed' 'Shoriful Islam' 'Mustafizur Rahman' 'M Theekshana'
 'Abdullah Shafique' 'Mahmudullah' 'KS Williamson' 'Shubman Gill'
 'Ikram Alikhil' 'C Karunaratne' 'CBRLS Kumara' 'JP Inglis' 'MP Stoinis'
 'G Coetzee' 'KA Maharaj' 'K Rabada' 'L Ngidi' 'Nasum Ahmed' 'Usama Mir'
 'MADI Hemantha' 'RR Hendricks' 'BA Stokes' 'DJ Willey' 'AAP Atkinson'
 'LH Ferguson' 'TA Boult' 'SA Yadav' 'RA Jadeja' 'Mohammed Shami'
 'Hasan Mahmud' 'Mohammad Wasim' 'T Shamsi' 'TM Head' 'JDS Neesham'
 'W Barresi' 'Shariz Ahmad' 'JJ Bumrah' 'Kuldeep Yadav' 'FDM Karunaratne'
 'AD Mathews' 'PVD Chameera' 'TG Southee']


unique in non_striker
['DJ Malan' 'JM Bairstow' 'JE Root' 'HC Brook' 'MM Ali' 'JC Buttler'
 'LS Livingstone' 'SM Curran' 'CR Woakes' 'AU Rashid' 'MA Wood' 'WA Young'
 'DP Conway' 'R Ravindra' 'Imam-ul-Haq' 'Fakhar Zaman' 'Babar Azam'
 'Mohammad Rizwan' 'Saud Shakeel' 'Iftikhar Ahmed' 'Mohammad Nawaz'
 'Shadab Khan' 'Shaheen Shah Afridi' 'Haris Rauf' "MP O'Dowd"
 'Vikramjit Singh' 'CN Ackermann' 'BFW de Leede' 'AT Nidamanuru'
 'Saqib Zulfiqar' 'RE van der Merwe' 'LV van Beek' 'A Dutt'
 'PA van Meekeren' 'Ibrahim Zadran' 'Rahmanullah Gurbaz' 'Rahmat Shah'
 'Hashmatullah Shahidi' 'Najibullah Zadran' 'Mohammad Nabi'
 'Azmatullah Omarzai' 'Rashid Khan' 'Mujeeb Ur Rahman' 'Naveen-ul-Haq'
 'Fazalhaq Farooqi' 'Liton Das' 'Tanzid Hasan' 'Mehedi Hasan Miraz'
 'Nazmul Hossain Shanto' 'Shakib Al Hasan' 'Mushfiqur Rahim' 'T Bavuma'
 'Q de Kock' 'HE van der Dussen' 'AK Markram' 'H Klaasen' 'DA Miller'
 'M Jansen' 'MDKJ Perera' 'P Nissanka' 'BKG Mendis' 'S Samarawickrama'
 'KIC Asalanka' 'DM de Silva' 'MD Shanaka' 'DN Wellalage' 'CAK Rajitha'
 'M Pathirana' 'D Madushanka' 'MR Marsh' 'DA Warner' 'SPD Smith'
 'M Labuschagne' 'GJ Maxwell' 'C Green' 'PJ Cummins' 'MA Starc' 'A Zampa'
 'JR Hazlewood' 'Ishan Kishan' 'RG Sharma' 'V Kohli' 'KL Rahul'
 'HH Pandya' 'DJ Mitchell' 'TWM Latham' 'GD Phillips' 'MS Chapman'
 'MJ Santner' 'MJ Henry' 'SA Edwards' 'SA Engelbrecht' 'R Klein'
 'RJW Topley' 'Towhid Hridoy' 'Mahedi Hasan' 'Taskin Ahmed'
 'Shoriful Islam' 'Mustafizur Rahman' 'M Theekshana' 'Abdullah Shafique'
 'SS Iyer' 'Mahmudullah' 'KS Williamson' 'Hasan Ali' 'Shubman Gill'
 'Ikram Alikhil' 'C Karunaratne' 'CBRLS Kumara' 'JP Inglis' 'MP Stoinis'
 'G Coetzee' 'KA Maharaj' 'K Rabada' 'L Ngidi' 'Nasum Ahmed' 'Usama Mir'
 'MADI Hemantha' 'RR Hendricks' 'BA Stokes' 'DJ Willey' 'AAP Atkinson'
 'LH Ferguson' 'SA Yadav' 'RA Jadeja' 'Mohammed Shami' 'Hasan Mahmud'
 'Mohammad Wasim' 'T Shamsi' 'TM Head' 'JDS Neesham' 'TA Boult'
 'W Barresi' 'Shariz Ahmad' 'JJ Bumrah' 'Kuldeep Yadav' 'FDM Karunaratne'
 'AD Mathews' 'PVD Chameera' 'TG Southee']


unique in bowler
['TA Boult' 'MJ Henry' 'MJ Santner' 'JDS Neesham' 'R Ravindra'
 'GD Phillips' 'CR Woakes' 'SM Curran' 'MA Wood' 'MM Ali' 'AU Rashid'
 'LS Livingstone' 'A Dutt' 'LV van Beek' 'CN Ackermann' 'PA van Meekeren'
 'BFW de Leede' 'RE van der Merwe' 'Vikramjit Singh' 'Saqib Zulfiqar'
 'Shaheen Shah Afridi' 'Hasan Ali' 'Haris Rauf' 'Iftikhar Ahmed'
 'Mohammad Nawaz' 'Shadab Khan' 'Taskin Ahmed' 'Shoriful Islam'
 'Mustafizur Rahman' 'Shakib Al Hasan' 'Mehedi Hasan Miraz' 'Mahmudullah'
 'Fazalhaq Farooqi' 'Mujeeb Ur Rahman' 'Naveen-ul-Haq' 'Rashid Khan'
 'Mohammad Nabi' 'Azmatullah Omarzai' 'CAK Rajitha' 'D Madushanka'
 'MD Shanaka' 'DM de Silva' 'M Pathirana' 'DN Wellalage' 'L Ngidi'
 'M Jansen' 'K Rabada' 'KA Maharaj' 'G Coetzee' 'JJ Bumrah'
 'Mohammed Siraj' 'HH Pandya' 'R Ashwin' 'Kuldeep Yadav' 'RA Jadeja'
 'MA Starc' 'JR Hazlewood' 'PJ Cummins' 'GJ Maxwell' 'C Green' 'A Zampa'
 'R Klein' 'LH Ferguson' 'Mahedi Hasan' 'RJW Topley' 'M Theekshana'
 'KIC Asalanka' 'SN Thakur' 'DJ Mitchell' 'JE Root' 'MP Stoinis'
 'CBRLS Kumara' 'C Karunaratne' 'V Kohli' 'Nasum Ahmed' 'Hasan Mahmud'
 'Usama Mir' 'MADI Hemantha' 'DJ Willey' 'AAP Atkinson' 'Mohammed Shami'
 'Noor Ahmad' 'MR Marsh' 'T Shamsi' 'LB Williams' 'AD Mathews'
 'AK Markram' 'Mohammad Wasim' 'Shariz Ahmad' 'PVD Chameera'
 'Nazmul Hossain Shanto' 'TG Southee']


unique in runs_off_bat
[0 6 1 4 2 3 5]


unique in extras
[0 1 3 4 5 2]


unique in wides
[0. 1. 3. 5. 2.]


unique in noballs
[0. 1.]

In [ ]:
filled['total_runs'] = filled.groupby(['match_id', 'innings'])['runs_off_bat'].cumsum() + filled.groupby(['match_id', 'innings'])['extras'].cumsum() + filled.groupby(['match_id', 'innings'])['wides'].cumsum() + filled.groupby(['match_id', 'innings'])['byes'].cumsum() + filled.groupby(['match_id', 'innings'])['legbyes'].cumsum()
filled['total_runs_off_bat'] = filled.groupby(['match_id', 'innings'])['runs_off_bat'].cumsum()
filled['total_extras'] = filled.groupby(['match_id', 'innings'])['extras'].cumsum()
filled['total_wides'] = filled.groupby(['match_id', 'innings'])['wides'].cumsum()
filled['total_noballs'] = filled.groupby(['match_id', 'innings'])['noballs'].cumsum()
filled['total_byes'] = filled.groupby(['match_id', 'innings'])['byes'].cumsum()
filled['total_legbyes'] = filled.groupby(['match_id', 'innings'])['legbyes'].cumsum()

In [248]:
filled

,match_id,venue,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,...,noballs,byes,legbyes,total_runs,total_runs_off_bat,total_extras,total_wides,total_noballs,total_byes,total_legbyes
0,1,"Narendra Modi Stadium, Ahmedabad",1,0.1,England,New Zealand,JM Bairstow,DJ Malan,TA Boult,0,...,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0
1,1,"Narendra Modi Stadium, Ahmedabad",1,0.2,England,New Zealand,JM Bairstow,DJ Malan,TA Boult,6,...,0.0,0.0,0.0,6.0,6,0,0.0,0.0,0.0,0.0
2,1,"Narendra Modi Stadium, Ahmedabad",1,0.3,England,New Zealand,JM Bairstow,DJ Malan,TA Boult,1,...,0.0,0.0,0.0,7.0,7,0,0.0,0.0,0.0,0.0
3,1,"Narendra Modi Stadium, Ahmedabad",1,0.4,England,New Zealand,DJ Malan,JM Bairstow,TA Boult,1,...,0.0,0.0,0.0,8.0,8,0,0.0,0.0,0.0,0.0
4,1,"Narendra Modi Stadium, Ahmedabad",1,0.5,England,New Zealand,JM Bairstow,DJ Malan,TA Boult,4,...,0.0,0.0,0.0,12.0,12,0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17375,32,"Maharashtra Cricket Association Stadium, Pune",2,34.5,New Zealand,South Africa,MJ Henry,GD Phillips,KA Maharaj,0,...,0.0,0.0,0.0,172.0,149,12,6.0,1.0,4.0,1.0
17376,32,"Maharashtra Cricket Association Stadium, Pune",2,34.6,New Zealand,South Africa,MJ Henry,GD Phillips,KA Maharaj,0,...,0.0,0.0,0.0,172.0,149,12,6.0,1.0,4.0,1.0
17377,32,"Maharashtra Cricket Association Stadium, Pune",2,35.1,New Zealand,South Africa,GD Phillips,MJ Henry,G Coetzee,0,...,0.0,0.0,0.0,172.0,149,12,6.0,1.0,4.0,1.0
17378,32,"Maharashtra Cricket Association Stadium, Pune",2,35.2,New Zealand,South Africa,GD Phillips,MJ Henry,G Coetzee,6,...,0.0,0.0,0.0,178.0,155,12,6.0,1.0,4.0,1.0
17379,32,"Maharashtra Cricket Association Stadium, Pune",2,35.3,New Zealand,South Africa,GD Phillips,MJ Henry,G Coetzee,0,...,0.0,0.0,0.0,178.0,155,12,6.0,1.0,4.0,1.0

In [ ]:
max_ball_indices = filled.groupby(['match_id', 'innings'])['ball'].idxmax()

# Create a new DataFrame with one entry per match and inning, including additional columns
result_df = filled.loc[max_ball_indices, ['match_id', 'innings', 'venue', 'ball', 'batting_team', 'bowling_team', 'total_runs',
                                       'total_runs_off_bat', 'total_extras', 'total_wides', 'total_noballs',
                                       'total_byes', 'total_legbyes']].reset_index(drop=True)

result_df.columns

Index(['match_id', 'innings', 'venue', 'ball', 'batting_team', 'bowling_team',
       'total_runs', 'total_runs_off_bat', 'total_extras', 'total_wides',
       'total_noballs', 'total_byes', 'total_legbyes'],
      dtype='object')

Considering noballs feature as our target variable and rest of the dataframe as features helpful in predicting noballs

In [ ]:
X = result_df.drop(columns='total_noballs')
Y = result_df['total_noballs']

Appling one hot label encoding
* One-hot encoding creates a binary matrix to represent the categories without implying any ordinal relationship between them.

In [ ]:
X_e = pd.get_dummies(X, columns=['match_id', 'innings', 'venue', 'batting_team', 'bowling_team',], prefix='Category')

Standardizing the data

In [ ]:
# Standardize the input features

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_es = scaler.fit_transform(X_e)

##Training linear regression model

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error



# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_es,Y, test_size=0.2, random_state=42)

# Create a Linear Regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
predictions = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, predictions)
print(f'Mean Squared Error: {mse}')

# Coefficients and intercept
coefficients = model.coef_
intercept = model.intercept_

Mean Squared Error: 1.9230769230769367

We have used the finals of our task 3 as a test case and will feed in the model and see the output:

In [269]:
result = result.head(1)
result

,match_id,innings,venue,ball,batting_team,bowling_team,total_extras,total_wides,total_runs_off_bat,total_runs,total_byes,total_legbyes
0,32,1,"Narendra Modi Stadium, Ahmedabad",50.0,India,South Africa,16,5.0,288,304.0,4.0,2.0

In [266]:
result = pd.concat([result, X], axis=0)
Xt_e = pd.get_dummies(result, columns=[ 'match_id','innings','venue', 'batting_team', 'bowling_team',], prefix='Category')
Xt_e = Xt_e.head(1)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_es = scaler.fit_transform(Xt_e)

Predicting for test case

In [270]:
predictions_lr = model.predict(X_es)
x = predictions_lr.flatten()

In [271]:
print(f'There will be {round(x)} noball in the first inning')

There will be 1 noball in the first inning

#Predicitng Total runs scored in final

Finding and replacing null values

In [ ]:
cd = [ 'season', 'start_date','other_wicket_type',
       'other_player_dismissed','penalty', 'player_dismissed',]
filled = deliveries.drop(columns=cd)
filled.isnull().sum()

match_id            0
venue               0
innings             0
ball                0
batting_team        0
bowling_team        0
striker             0
non_striker         0
bowler              0
runs_off_bat        0
extras              0
wides           16949
noballs         17338
byes            17354
legbyes         17263
wicket_type     16889
dtype: int64

In [ ]:
filled  = filled.fillna(0)
filled.isnull().sum()

match_id        0
venue           0
innings         0
ball            0
batting_team    0
bowling_team    0
striker         0
non_striker     0
bowler          0
runs_off_bat    0
extras          0
wides           0
noballs         0
byes            0
legbyes         0
wicket_type     0
dtype: int64

In [ ]:
filled.columns

Index(['match_id', 'venue', 'innings', 'ball', 'batting_team', 'bowling_team',
       'striker', 'non_striker', 'bowler', 'runs_off_bat', 'extras', 'wides',
       'noballs', 'byes', 'legbyes', 'wicket_type'],
      dtype='object')

Creating different columns of total runs, total runs off bat, total extras, total wides, total no balls, total byes, total legbyes etc and merging them with the data frame

In [ ]:
filled['total_runs'] = filled.groupby(['match_id', 'innings'])['runs_off_bat'].cumsum() + filled.groupby(['match_id', 'innings'])['extras'].cumsum() + filled.groupby(['match_id', 'innings'])['wides'].cumsum() + filled.groupby(['match_id', 'innings'])['byes'].cumsum() + filled.groupby(['match_id', 'innings'])['legbyes'].cumsum()
filled['total_runs_off_bat'] = filled.groupby(['match_id', 'innings'])['runs_off_bat'].cumsum()
filled['total_extras'] = filled.groupby(['match_id', 'innings'])['extras'].cumsum()
filled['total_wides'] = filled.groupby(['match_id', 'innings'])['wides'].cumsum()
filled['total_noballs'] = filled.groupby(['match_id', 'innings'])['noballs'].cumsum()
filled['total_byes'] = filled.groupby(['match_id', 'innings'])['byes'].cumsum()
filled['total_legbyes'] = filled.groupby(['match_id', 'innings'])['legbyes'].cumsum()

Here we have create a new df that has all inforamtion about match, venue, inning and respective total scores.

In [ ]:

max_ball_indices = filled.groupby(['match_id', 'innings'])['ball'].idxmax()

# Create a new DataFrame with one entry per match and inning, including additional columns
result_df = filled.loc[max_ball_indices, ['match_id', 'innings', 'venue', 'ball', 'batting_team', 'bowling_team',
                                         'total_runs', 'total_extras', 'total_wides', 'total_noballs',
                                       'total_byes', 'total_legbyes']].reset_index(drop=True)

result_df

,match_id,innings,venue,ball,batting_team,bowling_team,total_runs,total_extras,total_wides,total_noballs,total_byes,total_legbyes
0,1,1,"Narendra Modi Stadium, Ahmedabad",49.7,England,New Zealand,288.0,6,6.0,0.0,0.0,0.0
1,1,2,"Narendra Modi Stadium, Ahmedabad",36.2,New Zealand,England,291.0,8,3.0,0.0,4.0,1.0
2,2,1,"Rajiv Gandhi International Stadium, Uppal, Hyd...",48.6,Pakistan,Netherlands,294.0,9,8.0,1.0,0.0,0.0
3,2,2,"Rajiv Gandhi International Stadium, Uppal, Hyd...",40.7,Netherlands,Pakistan,214.0,9,9.0,0.0,0.0,0.0
4,3,1,"Himachal Pradesh Cricket Association Stadium, ...",37.2,Afghanistan,Bangladesh,164.0,8,8.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
59,30,2,"Maharashtra Cricket Association Stadium, Pune",45.2,Afghanistan,Sri Lanka,252.0,10,9.0,0.0,0.0,1.0
60,31,1,"Eden Gardens, Kolkata",45.1,Bangladesh,Pakistan,213.0,9,5.0,0.0,0.0,4.0
61,31,2,"Eden Gardens, Kolkata",32.3,Pakistan,Bangladesh,209.0,4,2.0,0.0,0.0,2.0
62,32,1,"Maharashtra Cricket Association Stadium, Pune",49.6,South Africa,New Zealand,369.0,12,8.0,0.0,0.0,4.0
63,32,2,"Maharashtra Cricket Association Stadium, Pune",35.3,New Zealand,South Africa,178.0,12,6.0,1.0,4.0,1.0

In [ ]:
X.columns

Index(['match_id', 'innings', 'venue', 'ball', 'batting_team', 'bowling_team',
       'total_extras', 'total_wides', 'total_noballs', 'total_byes',
       'total_legbyes'],
      dtype='object')

In [ ]:
X = result_df.drop(columns='total_runs')
Y = result_df['total_runs']

One-hot encoding the data

In [ ]:
X_e = pd.get_dummies(X, columns=[ 'match_id','innings','venue', 'batting_team', 'bowling_team',], prefix='Category')

In [ ]:
# Standardize the input features

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_es = scaler.fit_transform(X_e)

#Training the XGBoost model

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import xgboost as xgb

X_train, X_test, y_train, y_test = train_test_split(X_es, Y, test_size=0.2, random_state=42)

# Create an XGBoost model
model = xgb.XGBRegressor(objective ='reg:squarederror', colsample_bytree = 0.3, learning_rate = 0.1,
                max_depth = 5, alpha = 10, n_estimators = 10)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
predictions = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, predictions)
print(f'Mean Squared Error: {mse}')

Mean Squared Error: 3541.0766141535355

In [ ]:
import pandas as pd

# Assuming df is your original DataFrame with all the columns
# For demonstration purposes, let's create a sample DataFrame
data = {
    'match_id': [32],
    'innings': [1],
    'ball': [50],
    'venue': ['Narendra Modi Stadium, Ahmedabad'],
    'batting_team': ['India'],
    'bowling_team': ['South Africa'],
    "total_extras": [16],
    'total_wides': [5],
    'total_runs' : [304],
    'total_runs_off_bat' : [288],
    'total_byes': [4],
    'total_legbyes': [2],
}

df = pd.DataFrame(data)

# Group by 'match_id' and 'innings' and calculate the sum of relevant columns within each group
result = df.groupby(['match_id', 'innings', 'venue', 'ball', 'batting_team', 'bowling_team']).agg({
    'total_extras': 'sum',
    'total_wides': 'sum',
    'total_runs_off_bat':'sum',
    'total_runs':'sum',
    'total_byes': 'sum',
    'total_legbyes': 'sum'
}).reset_index()

In [ ]:
result = pd.concat([result_df, X], axis=0)
Xt_e = pd.get_dummies(result, columns=[ 'match_id','innings','venue', 'batting_team', 'bowling_team',], prefix='Category')
Xt_e = Xt_e.head(1)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_es = scaler.fit_transform(Xt_e)

X_es.shape

(1, 70)

In [ ]:
X_es.shape

(1, 70)

Predicting on test data

In [ ]:
predictions_t = model.predict(X_es)

1/1 [==============================] - 0s 21ms/step

In [ ]:
print(f"Team India will score {predictions_t} runs in final")

Team India will score 304 runs in final